version: '3'
services:
  app:
    image: 'scrapinghub/splash'
    container_name: 'splash'
    ports:
      - '8050:8050'
    volumes:
      - './data/splash:/etc/splash' # splash configuration
      - './data/scripts:/scripts' # scripts to be executed by splash
